---
title: "larvae_settlarvae <- read.csv("lement_mhw"
author: "JT Miller"
date: "12/8/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Loading in packages
```{r}
library(tidyverse)
library(heatwaveR)
library(ggplot2) # Message
```

```{r}
larvae <- read.csv("Invertebrate_Settlement_All_Years_20211004.csv", header=T, sep = ",", na.strings="-99999")
```

# Lets clean up the data
```{r}
larvae %>% 
  dplyr::select(SITE, DATE_RETRIEVED, DURATION, ARTHROPODA, BIVALVIA, GASTROPODA, OPHIUROIDEA_ASTERPODEA, S_PURPURATUS, M_FRANCISCANUS, TOTAL_URCHINS)
```
### Lets look at each group of larvae and divide out by duration. 
```{r}
larvae_p_day <- larvae %>%
  mutate(arthropods_per_day = (ARTHROPODA/DURATION)) %>% 
  mutate(bivalves_per_day = (BIVALVIA/DURATION)) %>% 
  mutate(gastropods_per_day = (GASTROPODA/DURATION)) %>% 
  mutate(stars_per_day = (OPHIUROIDEA_ASTERPODEA/DURATION)) %>% 
  mutate(purple_urchins_per_day = (S_PURPURATUS/DURATION)) %>% 
  mutate(mussels_per_day = (M_FRANCISCANUS/DURATION)) %>% 
  mutate(total_urchins_per_day = (TOTAL_URCHINS/DURATION))
```

### Now lets take group totals by day 
```{r}
larvae_avg_p_day <- larvae_p_day %>% 
  dplyr::group_by(DATE_RETRIEVED) %>% 
  mutate(avg_arthropods = mean(arthropods_per_day)) %>% 
  mutate(avg_bivalves = mean(bivalves_per_day)) %>% 
  mutate(avg_gastropods = mean(gastropods_per_day)) %>% 
  mutate(avg_stars = mean(stars_per_day)) %>% 
  mutate(avg_purps = mean(purple_urchins_per_day)) %>% 
  mutate(avg_mussels = mean(mussels_per_day)) %>% 
  mutate(avg_urchins = mean(total_urchins_per_day))

#And get rid of the extras

larvae_distinct <- larvae_avg_p_day %>% 
  distinct(DATE_RETRIEVED, .keep_all = TRUE)
```

### Lets try graphing one of the groups
```{r}
ggplot(data = larvae_distinct, aes(x = DATE_RETRIEVED, y = avg_arthropods, group = 1)) +
  geom_line()
#Well this looks reasonably interesting, however it really isnt in a readable form. Lets try to condense the measurements 
```
### Lets sum everything up by months and plot by month-year
```{r}
larvae_distinct$DATE_RETRIEVED_NEW <- strptime(as.character(larvae_distinct$DATE_RETRIEVED), "%m/%d/%Y")

format(larvae_distinct$DATE_RETRIEVED_NEW, "%m-%d-%Y")

larvae_distinct_df <- larvae_distinct %>% 
  mutate(month = format(DATE_RETRIEVED_NEW, "%m"), year = format(DATE_RETRIEVED_NEW, "%Y"), month_Year = format(DATE_RETRIEVED_NEW, "%Y-%m")) 


```

